[Unit]
Wants=pipewire.service wireplumber.service pipewire-pulse.service waybar.service
After=pipewire.service wireplumber.service pipewire-pulse.service waybar.service

[Service]
Restart=on-failure
RestartSec=2
ExecStartPre=/usr/bin/gdbus wait --session --timeout=10 org.kde.StatusNotifierWatcher
