[Unit]
Wants=pipewire.service wireplumber.service pipewire-pulse.service
After=pipewire.service wireplumber.service pipewire-pulse.service

[Service]
ExecStartPre=/usr/bin/gdbus wait --session --timeout=10 org.kde.StatusNotifierWatcher
